
services:
  api:
    build: .

    command: uvicorn app.main:api --reload --host 0.0.0.0 --port 8000
    #        uvicorn <pacote>.<arquivo>:<objeto_fastapi>


    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - __pycache__/
            - .vscode/
            - venv/
            - .pytest_cache/
            - .coverage
            - .env

        - action: rebuild
          path: ./requirements.txt

    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    restart: always

  worker_critical:
    build: .
    container_name: worker_critical
    command: celery -A app.celery_app worker -Q critical --loglevel=INFO
    depends_on:
      - rabbitmq
    restart: always

  worker_high:
    build: .
    container_name: worker_high
    command: celery -A app.celery_app  worker -Q high --loglevel=INFO
    depends_on:
      - rabbitmq
    restart: always

  worker_low:
    build: .
    container_name: worker_low
    command: celery -A app.celery_app  worker -Q low --loglevel=INFO
    depends_on:
      - rabbitmq
    restart: always


  beat:
    build: .
    container_name: celery_beat
    command: celery -A app.celery_app.app beat --loglevel=INFO
    depends_on:
      - redis
      - rabbitmq
    restart: always

  flower:
    image: mher/flower
    container_name: flower
    command: celery --broker=amqp://guest:guest@rabbitmq:5672// flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - rabbitmq
    restart: always

  redis:
    image: redis:7
    container_name: redis_queue
    ports:
      - "6379:6379"
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_redis
    ports:
      - "5672:5672"   # broker
      - "15672:15672" # painel de admin
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
